@token = <token>
@port = 3000

### Sign up
POST http://localhost:{{port}}/api/auth/sign-up
Content-Type: application/json

{
  "username": "emperor",
  "password": "password"
}

### Sign in
POST http://localhost:{{port}}/api/auth/sign-in
Content-Type: application/json

{
  "username": "emperor",
  "password": "password"
}

### Delete Account
DELETE http://localhost:{{port}}/api/auth/delete-user/
Authorization: Bearer {{token}}

### Logout
DELETE http://localhost:{{port}}/api/auth/logout
Authorization: Bearer {{token}}

### Logout All
DELETE http://localhost:{{port}}/api/auth/logout-all
Authorization: Bearer {{token}}