@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lcklkIjoiNjRlMjE4YmU3M2ExN2NjODE4ZTIxOGUzIiwidG9rZW5JZCI6IjY0ZTIxOGJlNzNhMTdjYzgxOGUyMThlNCIsImlhdCI6MTY5MjUzOTA3MX0.s0zoTt0Uplm-lugBiVwS0zABnLitVkT8XzaTr_SPpb4
@port = 3000

### Sign up
POST http://localhost:{{port}}/api/auth/sign-up
Content-Type: application/json

{
  "username": "emperor",
  "password": "password"
}

### Sign in
POST http://localhost:{{port}}/api/auth/sign-in
Content-Type: application/json

{
  "username": "emperor",
  "password": "password"
}

### Delete Account
DELETE http://localhost:{{port}}/api/auth/delete-user/
Authorization: Bearer {{token}}

### Logout
DELETE http://localhost:{{port}}/api/auth/logout
Authorization: Bearer {{token}}

### Logout All
DELETE http://localhost:{{port}}/api/auth/logout-all
Authorization: Bearer {{token}}

### Post content
POST http://localhost:{{port}}/api/posts/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "What even is lorem ipsum 1",
  "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id interdum velit laoreet id donec ultrices tincidunt arcu non. Ac ut consequat semper viverra. Tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Tellus in metus vulputate eu scelerisque felis. Nec nam aliquam sem et tortor. Ultricies mi quis hendrerit dolor magna eget. Libero nunc consequat interdum varius. Tortor at risus viverra adipiscing at. Etiam sit amet nisl purus in mollis nunc sed. Auctor eu augue ut lectus arcu bibendum at varius vel. Molestie a iaculis at erat pellentesque adipiscing commodo elit. Ac auctor augue mauris augue neque gravida in fermentum et. Sed arcu non odio euismod. Tincidunt dui ut ornare lectus sit amet est placerat. Urna condimentum mattis pellentesque id nibh tortor. Facilisis leo vel fringilla est. Sit amet nisl purus in mollis nunc sed id.",
  "guild": "test"
}

### Create Guild
POST http://localhost:{{port}}/api/guilds
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "test"
}

### Delete Guild
DELETE http://localhost:{{port}}/api/guilds/:guildName
Authorization: Bearer {{token}}

### Delete Post
DELETE http://localhost:{{port}}/api/posts/:postId
Authorization: Bearer {{token}}

### Get Posts
GET http://localhost:{{port}}/api/posts?number=15

### Get Guilds
GET http://localhost:{{port}}/api/guilds?number=15

### Get self guilds
GET http://localhost:{{port}}/api/user/guilds
Authorization: Bearer {{token}}

### Get guild posts
GET http://localhost:{{port}}/api/guilds/:guild/posts

### Get self posts
GET http://localhost:{{port}}/api/user/posts
Authorization: Bearer {{token}}

### Optional
GET http://localhost:{{port}}/api/user/posts?flattened=true
Authorization: Bearer {{token}}

### Get a specific user's posts
GET http://localhost:{{port}}/api/user/:user/posts

### Optional
GET http://localhost:{{port}}/api/user/:user/posts?flattened=true

### Get a specific user's guilds
GET http://localhost:{{port}}/api/user/:user/guilds

### Like Post
GET http://localhost:{{port}}/api/posts/:id/like
Authorization: Bearer {{token}}

### dislike Post
GET http://localhost:{{port}}/api/posts/:id/dislike
Authorization: Bearer {{token}}

### Patch Posts
PATCH http://localhost:{{port}}/api/posts/:id
Authorization: Bearer {{token}}
# providing title and content both is not required.
{
  "title": "a title",
  "content": "a content"
}
